// menus for stats

export const acctStatMenus = {
  activityModeOptions: [
    { text: 'All PvE', value: 'allPvE' },
    { text: 'Story', value: 'story' },
    { text: 'Patrol', value: 'patrol' },
    { text: 'Normal Strikes', value: 'strike' },
    { text: 'Nightfall Strikes', value: 'nightfall' },
    { text: 'Raid', value: 'raid' },
    { text: 'All Crucible', value: 'allPvP' },
    { text: 'Control', value: 'control' },
    { text: 'Clash', value: 'clash' },
    { text: 'Supremacy', value: 'supremacy' },
    { text: 'Survival', value: 'survival' },
    { text: 'Countdown', value: 'countdown' },
    { text: 'Trials of the Nine', value: 'trialsofthenine' },
    { text: 'Iron Banner', value: 'ironBanner' }
  ],
  statIdOptions: [
    { text: 'Ability Kills', value: 'weaponKillsAbility' },
    { text: 'Auto Rifle Accuracy', value: 'weaponKillsPrecisionKillsAutoRifle' },
    { text: 'Auto Rifle Kills', value: 'weaponKillsAutoRifle' },
    { text: 'Auto Rifle Precision Kills', value: 'weaponPrecisionKillsAutoRifle' },
    { text: 'Fusion Rifle Accuracy', value: 'weaponKillsPrecisionKillsFusionRifle' },
    { text: 'Fusion Rifle Kills', value: 'weaponKillsFusionRifle' },
    { text: 'Fusion Rifle Precision Kills', value: 'weaponPrecisionKillsFusionRifle' },
    { text: 'Grenade Accuracy', value: 'weaponKillsPrecisionKillsGrenade' },
    { text: 'Grenade Kills', value: 'weaponKillsGrenade' },
    { text: 'Grenade Launcher  Accuracy', value: 'weaponKillsPrecisionKillsGrenadeLauncher' },
    { text: 'Grenade Launcher Kills', value: 'weaponKillsGrenadeLauncher' },
    { text: 'Grenade Launcher Precision Kills', value: 'weaponPrecisionKillsGrenadeLauncher' },
    { text: 'Grenade Precision Kills', value: 'weaponPrecisionKillsGrenade' },
    { text: 'Hand Cannon Accuracy', value: 'weaponKillsPrecisionKillsHandCannon' },
    { text: 'Hand Cannon Kills', value: 'weaponKillsHandCannon' },
    { text: 'Hand Cannon Precision Kills', value: 'weaponPrecisionKillsHandCannon' },
    { text: 'Machine Gun Accuracy', value: 'weaponKillsPrecisionKillsMachinegun' },
    { text: 'Machine Gun Kills', value: 'weaponKillsMachinegun' },
    { text: 'Machine Gun Precision Kills', value: 'weaponPrecisionKillsMachinegun' },
    { text: 'Melee Accuracy', value: 'weaponKillsPrecisionKillsMelee' },
    { text: 'Melee Kills', value: 'weaponKillsMelee' },
    { text: 'Melee Precision Kills', value: 'weaponPrecisionKillsMelee' },
    { text: 'Pulse Rifle Accuracy', value: 'weaponKillsPrecisionKillsPulseRifle' },
    { text: 'Pulse Rifle Kills', value: 'weaponKillsPulseRifle' },
    { text: 'Pulse Rifle Precision Kills ', value: 'weaponPrecisionKillsPulseRifle' },
    { text: 'Relic  Accuracy', value: 'weaponKillsPrecisionKillsRelic' },
    { text: 'Relic Precision Kills', value: 'weaponPrecisionKillsRelic' },
    { text: 'Relics Kills', value: 'weaponKillsRelic' },
    { text: 'Rocket Launcher Accuracy', value: 'weaponKillsPrecisionKillsRocketLauncher' },
    { text: 'Rocket Launcher Kills', value: 'weaponKillsRocketLauncher' },
    { text: 'Rocket Launcher Precision Kills', value: 'weaponPrecisionKillsRocketLauncher' },
    { text: 'Scout Rifle Accuracy ', value: 'weaponKillsPrecisionKillsScoutRifle' },
    { text: 'Scout Rifle Kills', value: 'weaponKillsScoutRifle' },
    { text: 'Scout Rifle Precision Kills', value: 'weaponPrecisionKillsScoutRifle' },
    { text: 'Shotgun Accuracy', value: 'weaponKillsPrecisionKillsShotgun' },
    { text: 'Shotgun Kills', value: 'weaponKillsShotgun' },
    { text: 'Shotgun Precision Kills', value: 'weaponPrecisionKillsShotgun' },
    { text: 'Sidearm  Accuracy', value: 'weaponKillsPrecisionKillsSideArm' },
    { text: 'Sidearm Kills', value: 'weaponKillsSideArm' },
    { text: 'Sidearm Precision Kills', value: 'weaponPrecisionKillsSideArm' },
    { text: 'Sniper Rifle Accuracy ', value: 'weaponKillsPrecisionKillsSniper' },
    { text: 'Sniper Rifle Kills', value: 'weaponKillsSniper' },
    { text: 'Sniper Rifle Precision Kills', value: 'weaponPrecisionKillsSniper' },
    { text: 'Submachine Gun Accuracy', value: 'weaponKillsPrecisionKillsSubmachinegun' },
    { text: 'Submachine Gun Kills', value: 'weaponKillsSubmachinegun' },
    { text: 'Submachine Gun Precision Kills', value: 'weaponPrecisionKillsSubmachinegun' },
    { text: 'Super Accuracy', value: 'weaponKillsPrecisionKillsSuper' },
    { text: 'Super Kills', value: 'weaponKillsSuper' },
    { text: 'Super Precision Kills', value: 'weaponPrecisionKillsSuper' },
    { text: 'Sword Kills', value: 'weaponKillsSword' }
  ]
}
