// test menus

export const generalMenus = {
  allianceOptions: [
    { text: 'Wookieville', value: '2' },
    { text: 'Dome Busters', value: '1' }
  ]
}

export const acctStatMenus = {
  activityModeOptions: [
    { text: 'All PvE', value: 'allPvE' },
    { text: 'Story', value: 'story' },
    { text: 'Patrol', value: 'patrol' },
    { text: 'Normal Strikes', value: 'strike' },
    { text: 'Nightfall Strikes', value: 'nightfall' },
    { text: 'Raid', value: 'raid' },
    { text: 'All Crucible', value: 'allPvP' },
    { text: 'Control', value: 'control' },
    { text: 'Clash', value: 'clash' },
    { text: 'Supremacy', value: 'supremacy' },
    { text: 'Survival', value: 'survival' },
    { text: 'Countdown', value: 'countdown' },
    { text: 'Trials of the Nine', value: 'trialsofthenine' },
    { text: 'Iron Banner', value: 'ironBanner' }
  ],
  pveActivityModeOptions: [
    { text: 'All PvE', value: 'allPvE' },
    { text: 'Story', value: 'story' },
    { text: 'Patrol', value: 'patrol' },
    { text: 'Normal Strikes', value: 'strike' },
    { text: 'Nightfall Strikes', value: 'nightfall' },
    { text: 'Raid', value: 'raid' }
  ],
  pvpActivityModeOptions: [
    { text: 'All Crucible', value: 'allPvP' },
    { text: 'Control', value: 'control' },
    { text: 'Clash', value: 'clash' },
    { text: 'Supremacy', value: 'supremacy' },
    { text: 'Survival', value: 'survival' },
    { text: 'Countdown', value: 'countdown' },
    { text: 'Trials of the Nine', value: 'trialsofthenine' },
    { text: 'Iron Banner', value: 'ironBanner' }
  ],
  pveStatIdOptions: [
    { text: 'Kills', value: 'kills' },
    { text: 'Precision Kills', value: 'precisionKills' },
    { text: 'Assists', value: 'assists' },
    { text: 'Deaths', value: 'deaths' },
    { text: 'Suicides', value: 'suicides' },
    { text: 'Kills+Assists/Deaths Ratio', value: 'killsDeathsAssists' },
    { text: 'Kills/Deaths Ratio', value: 'killsDeathsRatio' },
    { text: 'Most Precision Kills', value: 'mostPrecisionKills' },
    { text: 'Longest Kill Distance', value: 'longestKillDistance' },
    { text: 'Longest Kill Streak', value: 'longestKillSpree' },
    { text: 'Longest Single Life', value: 'longestSingleLife' },
    { text: 'Average Kill Distance', value: 'averageKillDistance' },
    { text: 'Average Lifespan', value: 'averageLifespan' },
    { text: 'Orbs Dropped', value: 'orbsDropped' },
    { text: 'Orbs Gathered', value: 'orbsGathered' },
    { text: 'Resurrections Performed', value: 'resurrectionsPerformed' },
    { text: 'Resurrections Received', value: 'resurrectionsReceived' },
    { text: 'Ability Kills', value: 'weaponKillsAbility' },
    { text: 'Auto Rifle Kills', value: 'weaponKillsAutoRifle' },
    { text: 'Auto Rifle Precision Kills', value: 'weaponPrecisionKillsAutoRifle' },
    { text: 'Auto Rifle Accuracy', value: 'weaponKillsPrecisionKillsAutoRifle' },
    { text: 'Fusion Rifle Kills', value: 'weaponKillsFusionRifle' },
    { text: 'Fusion Rifle Precision Kills', value: 'weaponPrecisionKillsFusionRifle' },
    { text: 'Fusion Rifle Accuracy', value: 'weaponKillsPrecisionKillsFusionRifle' },
    { text: 'Grenade Kills', value: 'weaponKillsGrenade' },
    { text: 'Grenade Precision Kills', value: 'weaponPrecisionKillsGrenade' },
    { text: 'Grenade Accuracy', value: 'weaponKillsPrecisionKillsGrenade' },
    { text: 'Grenade Launcher Kills', value: 'weaponKillsGrenadeLauncher' },
    { text: 'Grenade Launcher Precision Kills', value: 'weaponPrecisionKillsGrenadeLauncher' },
    { text: 'Grenade Launcher  Accuracy', value: 'weaponKillsPrecisionKillsGrenadeLauncher' },
    { text: 'Hand Cannon Kills', value: 'weaponKillsHandCannon' },
    { text: 'Hand Cannon Precision Kills', value: 'weaponPrecisionKillsHandCannon' },
    { text: 'Hand Cannon Accuracy', value: 'weaponKillsPrecisionKillsHandCannon' },
    { text: 'Machine Gun Kills', value: 'weaponKillsMachinegun' },
    { text: 'Machine Gun Precision Kills', value: 'weaponPrecisionKillsMachinegun' },
    { text: 'Machine Gun Accuracy', value: 'weaponKillsPrecisionKillsMachinegun' },
    { text: 'Melee Kills', value: 'weaponKillsMelee' },
    { text: 'Melee Precision Kills', value: 'weaponPrecisionKillsMelee' },
    { text: 'Melee Accuracy', value: 'weaponKillsPrecisionKillsMelee' },
    { text: 'Pulse Rifle Kills', value: 'weaponKillsPulseRifle' },
    { text: 'Pulse Rifle Precision Kills ', value: 'weaponPrecisionKillsPulseRifle' },
    { text: 'Pulse Rifle Accuracy', value: 'weaponKillsPrecisionKillsPulseRifle' },
    { text: 'Relics Kills', value: 'weaponKillsRelic' },
    { text: 'Relic Precision Kills', value: 'weaponPrecisionKillsRelic' },
    { text: 'Relic  Accuracy', value: 'weaponKillsPrecisionKillsRelic' },
    { text: 'Rocket Launcher Kills', value: 'weaponKillsRocketLauncher' },
    { text: 'Rocket Launcher Precision Kills', value: 'weaponPrecisionKillsRocketLauncher' },
    { text: 'Rocket Launcher Accuracy', value: 'weaponKillsPrecisionKillsRocketLauncher' },
    { text: 'Scout Rifle Kills', value: 'weaponKillsScoutRifle' },
    { text: 'Scout Rifle Precision Kills', value: 'weaponPrecisionKillsScoutRifle' },
    { text: 'Scout Rifle Accuracy ', value: 'weaponKillsPrecisionKillsScoutRifle' },
    { text: 'Shotgun Kills', value: 'weaponKillsShotgun' },
    { text: 'Shotgun Precision Kills', value: 'weaponPrecisionKillsShotgun' },
    { text: 'Shotgun Accuracy', value: 'weaponKillsPrecisionKillsShotgun' },
    { text: 'Sidearm Kills', value: 'weaponKillsSideArm' },
    { text: 'Sidearm Precision Kills', value: 'weaponPrecisionKillsSideArm' },
    { text: 'Sidearm  Accuracy', value: 'weaponKillsPrecisionKillsSideArm' },
    { text: 'Sniper Rifle Kills', value: 'weaponKillsSniper' },
    { text: 'Sniper Rifle Precision Kills', value: 'weaponPrecisionKillsSniper' },
    { text: 'Sniper Rifle Accuracy ', value: 'weaponKillsPrecisionKillsSniper' },
    { text: 'Submachine Gun Kills', value: 'weaponKillsSubmachinegun' },
    { text: 'Submachine Gun Precision Kills', value: 'weaponPrecisionKillsSubmachinegun' },
    { text: 'Submachine Gun Accuracy', value: 'weaponKillsPrecisionKillsSubmachinegun' },
    { text: 'Super Kills', value: 'weaponKillsSuper' },
    { text: 'Super Precision Kills', value: 'weaponPrecisionKillsSuper' },
    { text: 'Super Accuracy', value: 'weaponKillsPrecisionKillsSuper' },
    { text: 'Sword Kills', value: 'weaponKillsSword' }
  ],
  pvpStatIdOptions: [
    { text: 'Activities Entered', value: 'activitiesEntered' },
    { text: 'Activities Won', value: 'activitiesWon' },
    { text: 'Win/Loss Ratio', value: 'winLossRatio' },
    { text: 'Average Score Per Kill', value: 'averageScorePerKill' },
    { text: 'Average Score Per Life', value: 'averageScorePerLife' },
    { text: 'Best Single Game Kills', value: 'bestSingleGameKills' },
    { text: 'Best Single Game Score', value: 'bestSingleGameScore' },
    { text: 'Kills', value: 'kills' },
    { text: 'Precision Kills', value: 'precisionKills' },
    { text: 'Assists', value: 'assists' },
    { text: 'Deaths', value: 'deaths' },
    { text: 'Suicides', value: 'suicides' },
    { text: 'Kills+Assists/Deaths Ratio', value: 'killsDeathsAssists' },
    { text: 'Kills/Deaths Ratio', value: 'killsDeathsRatio' },
    { text: 'Most Precision Kills', value: 'mostPrecisionKills' },
    { text: 'Longest Kill Distance', value: 'longestKillDistance' },
    { text: 'Longest Kill Streak', value: 'longestKillSpree' },
    { text: 'Longest Single Life', value: 'longestSingleLife' },
    { text: 'Average Kill Distance', value: 'averageKillDistance' },
    { text: 'Average Lifespan', value: 'averageLifespan' },
    { text: 'Orbs Dropped', value: 'orbsDropped' },
    { text: 'Orbs Gathered', value: 'orbsGathered' },
    { text: 'Resurrections Performed', value: 'resurrectionsPerformed' },
    { text: 'Resurrections Received', value: 'resurrectionsReceived' },
    { text: 'Ability Kills', value: 'weaponKillsAbility' },
    { text: 'Auto Rifle Kills', value: 'weaponKillsAutoRifle' },
    { text: 'Auto Rifle Precision Kills', value: 'weaponPrecisionKillsAutoRifle' },
    { text: 'Auto Rifle Accuracy', value: 'weaponKillsPrecisionKillsAutoRifle' },
    { text: 'Fusion Rifle Kills', value: 'weaponKillsFusionRifle' },
    { text: 'Fusion Rifle Precision Kills', value: 'weaponPrecisionKillsFusionRifle' },
    { text: 'Fusion Rifle Accuracy', value: 'weaponKillsPrecisionKillsFusionRifle' },
    { text: 'Grenade Kills', value: 'weaponKillsGrenade' },
    { text: 'Grenade Precision Kills', value: 'weaponPrecisionKillsGrenade' },
    { text: 'Grenade Accuracy', value: 'weaponKillsPrecisionKillsGrenade' },
    { text: 'Grenade Launcher Kills', value: 'weaponKillsGrenadeLauncher' },
    { text: 'Grenade Launcher Precision Kills', value: 'weaponPrecisionKillsGrenadeLauncher' },
    { text: 'Grenade Launcher  Accuracy', value: 'weaponKillsPrecisionKillsGrenadeLauncher' },
    { text: 'Hand Cannon Kills', value: 'weaponKillsHandCannon' },
    { text: 'Hand Cannon Precision Kills', value: 'weaponPrecisionKillsHandCannon' },
    { text: 'Hand Cannon Accuracy', value: 'weaponKillsPrecisionKillsHandCannon' },
    { text: 'Machine Gun Kills', value: 'weaponKillsMachinegun' },
    { text: 'Machine Gun Precision Kills', value: 'weaponPrecisionKillsMachinegun' },
    { text: 'Machine Gun Accuracy', value: 'weaponKillsPrecisionKillsMachinegun' },
    { text: 'Melee Kills', value: 'weaponKillsMelee' },
    { text: 'Melee Precision Kills', value: 'weaponPrecisionKillsMelee' },
    { text: 'Melee Accuracy', value: 'weaponKillsPrecisionKillsMelee' },
    { text: 'Pulse Rifle Kills', value: 'weaponKillsPulseRifle' },
    { text: 'Pulse Rifle Precision Kills ', value: 'weaponPrecisionKillsPulseRifle' },
    { text: 'Pulse Rifle Accuracy', value: 'weaponKillsPrecisionKillsPulseRifle' },
    { text: 'Relics Kills', value: 'weaponKillsRelic' },
    { text: 'Relic Precision Kills', value: 'weaponPrecisionKillsRelic' },
    { text: 'Relic  Accuracy', value: 'weaponKillsPrecisionKillsRelic' },
    { text: 'Rocket Launcher Kills', value: 'weaponKillsRocketLauncher' },
    { text: 'Rocket Launcher Precision Kills', value: 'weaponPrecisionKillsRocketLauncher' },
    { text: 'Rocket Launcher Accuracy', value: 'weaponKillsPrecisionKillsRocketLauncher' },
    { text: 'Scout Rifle Kills', value: 'weaponKillsScoutRifle' },
    { text: 'Scout Rifle Precision Kills', value: 'weaponPrecisionKillsScoutRifle' },
    { text: 'Scout Rifle Accuracy ', value: 'weaponKillsPrecisionKillsScoutRifle' },
    { text: 'Shotgun Kills', value: 'weaponKillsShotgun' },
    { text: 'Shotgun Precision Kills', value: 'weaponPrecisionKillsShotgun' },
    { text: 'Shotgun Accuracy', value: 'weaponKillsPrecisionKillsShotgun' },
    { text: 'Sidearm Kills', value: 'weaponKillsSideArm' },
    { text: 'Sidearm Precision Kills', value: 'weaponPrecisionKillsSideArm' },
    { text: 'Sidearm  Accuracy', value: 'weaponKillsPrecisionKillsSideArm' },
    { text: 'Sniper Rifle Kills', value: 'weaponKillsSniper' },
    { text: 'Sniper Rifle Precision Kills', value: 'weaponPrecisionKillsSniper' },
    { text: 'Sniper Rifle Accuracy ', value: 'weaponKillsPrecisionKillsSniper' },
    { text: 'Submachine Gun Kills', value: 'weaponKillsSubmachinegun' },
    { text: 'Submachine Gun Precision Kills', value: 'weaponPrecisionKillsSubmachinegun' },
    { text: 'Submachine Gun Accuracy', value: 'weaponKillsPrecisionKillsSubmachinegun' },
    { text: 'Super Kills', value: 'weaponKillsSuper' },
    { text: 'Super Precision Kills', value: 'weaponPrecisionKillsSuper' },
    { text: 'Super Accuracy', value: 'weaponKillsPrecisionKillsSuper' },
    { text: 'Sword Kills', value: 'weaponKillsSword' }
  ],
  medalStatIdOptions: [
    { text: 'All Medals Earned', value: 'allMedalsEarned' },
    { text: 'Medal Dawnblade Aerial*', value: 'medalAbilityDawnbladeAerial' },
    { text: 'Medal Dawnblade Slam*', value: 'medalAbilityDawnbladeSlam' },
    { text: 'Hurricane', value: 'medalAbilityFlowwalkerMulti' },
    { text: 'Lightning Strike', value: 'medalAbilityFlowwalkerQuick' },
    { text: 'Handfull of Bullets', value: 'medalAbilityGunslingerMulti' },
    { text: 'Lethal Instinct', value: 'medalAbilityGunslingerQuick' },
    { text: 'Medal Striker Combo*', value: 'medalAbilityJuggernautCombo' },
    { text: 'Medal Striker Slam*', value: 'medalAbilityJuggernautSlam' },
    { text: 'Medal Nighstalker Long Range*', value: 'medalAbilityNightstalkerLongRange' },
    { text: 'Entangled', value: 'medalAbilityNightstalkerTetherQuick' },
    { text: 'Medal Sentinel Combo*', value: 'medalAbilitySentinelCombo' },
    { text: 'Medal Sentinel Ward*', value: 'medalAbilitySentinelWard' },
    { text: 'Medal Stormcaller Landfall*', value: 'medalAbilityStormcallerLandfall' },
    { text: 'Lightning Storm', value: 'medalAbilityStormcallerMulti' },
    { text: 'Medal Sunbreaker Long Range*', value: 'medalAbilitySunbreakerLongRange' },
    { text: 'Everything Looks Like a Nail', value: 'medalAbilitySunbreakerMulti' },
    { text: 'Medal Voidwalker Distance*', value: 'medalAbilityVoidwalkerDistance' },
    { text: 'Medal Voidwalker Vortex*', value: 'medalAbilityVoidwalkerVortex' },
    { text: 'Blood for Blood', value: 'medalAvenger' },
    { text: 'I Live Here Now', value: 'medalControlAdvantageHold' },
    { text: 'Flag Bearer*', value: 'medalControlAdvantageStreak' },
    { text: 'Medal Control Capture All Zones*', value: 'medalControlCaptureAllZones' },
    { text: 'Flag Bearer*', value: 'medalControlMostAdvantage' },
    { text: 'Medal Control Perimeter Kill*', value: 'medalControlPerimeterKill' },
    { text: 'Power Overwhelming', value: 'medalControlPowerPlayWipe' },
    { text: 'Medal CountDown Defense*', value: 'medalCountdownDefense' },
    { text: 'Medal Countdown Defused Last Stand*', value: 'medalCountdownDefusedLastStand' },
    { text: 'Medal Countdown Defused Multi*', value: 'medalCountdownDefusedMulti' },
    { text: 'Medal Countdown Detonated*', value: 'medalCountdownDetonated' },
    { text: 'Medal Countdown Perfect*', value: 'medalCountdownPerfect' },
    { text: 'Gangs All Here', value: 'medalCountdownRoundAllAlive' },
    { text: 'The Cycle', value: 'medalCycle' },
    { text: 'Dodge This', value: 'medalDefeatHunterDodge' },
    { text: 'Barricade Breaker', value: 'medalDefeatTitanBrace' },
    { text: 'Rift Breaker', value: 'medalDefeatWarlockSigil' },
    { text: 'Not on My Watch', value: 'medalDefense' },
    { text: 'Crushed Them', value: 'medalMatchBlowout' },
    { text: 'Medal Match Comeback*', value: 'medalMatchComeback' },
    { text: 'Fight Me!', value: 'medalMatchMostDamage' },
    { text: 'Never In Doubt', value: 'medalMatchNeverTrailed' },
    { text: 'Time and a Half', value: 'medalMatchOvertime' },
    { text: 'Undefeated', value: 'medalMatchUndefeated' },
    { text: 'Double Play', value: 'medalMulti2x' },
    { text: 'Triple Play', value: 'medalMulti3x' },
    { text: 'Lights Out', value: 'medalMulti4x' },
    { text: 'Annihilation', value: 'medalMultiEntireTeam' },
    { text: 'Best Served Cold', value: 'medalPayback' },
    { text: 'Quick Strike', value: 'medalQuickStrike' },
    { text: 'Unyielding', value: 'medalStreak10x' },
    { text: 'Ruthless', value: 'medalStreak5x' },
    { text: 'We Ran Out of Medals', value: 'medalStreakAbsurd' },
    { text: 'Combined Fire', value: 'medalStreakCombined' },
    { text: 'Shutdown', value: 'medalStreakShutdown' },
    { text: 'Wrecking Crew', value: 'medalStreakTeam' },
    { text: 'Not So Fast My Friend', value: 'medalSuperShutdown' },
    { text: 'Medal Supremacy Crest Credit Streak*', value: 'medalSupremacyCrestCreditStreak' },
    { text: 'Medal Supremacy First Crest*', value: 'medalSupremacyFirstCrest' },
    { text: 'My Crest Is My Own', value: 'medalSupremacyNeverCollected' },
    { text: 'Medal Supremacy Perfect Secure Rate*', value: 'medalSupremacyPerfectSecureRate' },
    { text: 'Medal Supremacy Recover Streak*', value: 'medalSupremacyRecoverStreak' },
    { text: 'Safe and Secured', value: 'medalSupremacySecureStreak' },
    { text: 'Medal Survival Comeback*', value: 'medalSurvivalComeback' },
    { text: 'Undertaker', value: 'medalSurvivalKnockout' },
    { text: 'Medal Survival Quick Wipe*', value: 'medalSurvivalQuickWipe' },
    { text: 'Medal Survival Team Undefeated*', value: 'medalSurvivalTeamUndefeated' },
    { text: 'Survivor', value: 'medalSurvivalUndefeated' },
    { text: 'Medal Survival Win Last Stand*', value: 'medalSurvivalWinLastStand' },
    { text: 'Medal Unknown*', value: 'medalUnknown' },
    { text: 'Assault Specialist', value: 'medalWeaponAuto' },
    { text: 'Cold Fusion', value: 'medalWeaponFusion' },
    { text: 'Direct Hit', value: 'medalWeaponGrenade' },
    { text: 'Hawkeye', value: 'medalWeaponHandCannon' },
    { text: 'Lethal Cadence', value: 'medalWeaponPulse' },
    { text: 'Splash Damage', value: 'medalWeaponRocket' },
    { text: 'Field Scout', value: 'medalWeaponScout' },
    { text: 'Close Encounters', value: 'medalWeaponShotgun' },
    { text: 'Medal Sidearm*', value: 'medalWeaponSidearm' },
    { text: 'Sub Machinist', value: 'medalWeaponSmg' },
    { text: 'Medal Sniper Rifle*', value: 'medalWeaponSniper' },
    { text: 'Regent', value: 'medalWeaponSword' }
  ],
  statIdOptions: [
    { text: 'Activities Cleared', value: 'activitiesCleared' },
    { text: 'Activities Entered', value: 'activitiesEntered' },
    { text: 'Activities Won', value: 'activitiesWon' },
    { text: 'Activity Assists', value: 'activityAssists' },
    { text: 'Activity Best Goals Hit', value: 'activityBestGoalsHit' },
    { text: 'Activity Best Single Game Score', value: 'activityBestSingleGameScore' },
    { text: 'Activity Completions', value: 'activityCompletions' },
    { text: 'Activity Deaths', value: 'activityDeaths' },
    { text: 'Activity Duration', value: 'activityDurationSeconds' },
    { text: 'Activity Goals Hit', value: 'activityGoalsHit' },
    { text: 'Activity Goals Missed', value: 'activityGoalsMissed' },
    { text: 'Activity Kills', value: 'activityKills' },
    { text: 'Activity Kills+Assists/Deaths Ratio', value: 'activityKillsDeathsAssists' },
    { text: 'Activity Kills/Deaths Ratio', value: 'activityKillsDeathsRatio' },
    { text: 'Activity Precision Kills', value: 'activityPrecisionKills' },
    { text: 'Activity Time Played', value: 'activitySecondsPlayed' },
    { text: 'Activity Special Actions', value: 'activitySpecialActions' },
    { text: 'Activity Special Score', value: 'activitySpecialScore' },
    { text: 'Activity Wins', value: 'activityWins' },
    { text: 'Adventures Completed', value: 'adventuresCompleted' },
    { text: 'All Medals Earned', value: 'allMedalsEarned' },
    { text: 'All Participants Count', value: 'allParticipantsCount' },
    { text: 'All Participants Score', value: 'allParticipantsScore' },
    { text: 'All Participants Time Played', value: 'allParticipantsTimePlayed' },
    { text: 'Assists', value: 'assists' },
    { text: 'Average Death Distance', value: 'averageDeathDistance' },
    { text: 'Average Kill Distance', value: 'averageKillDistance' },
    { text: 'Average Lifespan', value: 'averageLifespan' },
    { text: 'Average Score Per Kill', value: 'averageScorePerKill' },
    { text: 'Average Score Per Life', value: 'averageScorePerLife' },
    { text: 'Best Single Game Kills', value: 'bestSingleGameKills' },
    { text: 'Best Single Game Score', value: 'bestSingleGameScore' },
    { text: 'Combat Rating', value: 'combatRating' },
    { text: 'Completed Game', value: 'completed' },
    { text: 'Control Zones Defensive Kills', value: 'controlZoneDefensiveKills' },
    { text: 'Control Zones Offensive Kills', value: 'controlZoneOffensiveKills' },
    { text: 'Control Zones Captured', value: 'controlZonesCaptured' },
    { text: 'Control Zones Neutralized', value: 'controlZonesNeutralized' },
    { text: 'Deaths', value: 'deaths' },
    { text: 'Efficiency', value: 'efficiency' },
    { text: 'Fastest Completion Time', value: 'fastestCompletionMs' },
    { text: 'Fastest Completion Time For Activity', value: 'fastestCompletionMsForActivity' },
    { text: 'Heroic Public Events Completed', value: 'heroicPublicEventsCompleted' },
    { text: 'Kills', value: 'kills' },
    { text: 'Kills+Assists/Deaths Ratio', value: 'killsDeathsAssists' },
    { text: 'Kills/Deaths Ratio', value: 'killsDeathsRatio' },
    { text: 'Longest Kill Streak', value: 'longestKillSpree' },
    { text: 'Longest Single Life', value: 'longestSingleLife' },
    { text: 'Medal Dawnblade Aerial*', value: 'medalAbilityDawnbladeAerial' },
    { text: 'Medal Dawnblade Slam*', value: 'medalAbilityDawnbladeSlam' },
    { text: 'Hurricane', value: 'medalAbilityFlowwalkerMulti' },
    { text: 'Lightning Strike', value: 'medalAbilityFlowwalkerQuick' },
    { text: 'Handfull of Bullets', value: 'medalAbilityGunslingerMulti' },
    { text: 'Lethal Instinct', value: 'medalAbilityGunslingerQuick' },
    { text: 'Medal Striker Combo*', value: 'medalAbilityJuggernautCombo' },
    { text: 'Medal Striker Slam*', value: 'medalAbilityJuggernautSlam' },
    { text: 'Medal Nighstalker Long Range*', value: 'medalAbilityNightstalkerLongRange' },
    { text: 'Entangled', value: 'medalAbilityNightstalkerTetherQuick' },
    { text: 'Medal Sentinel Combo*', value: 'medalAbilitySentinelCombo' },
    { text: 'Medal Sentinel Ward*', value: 'medalAbilitySentinelWard' },
    { text: 'Medal Stormcaller Landfall*', value: 'medalAbilityStormcallerLandfall' },
    { text: 'Lightning Storm', value: 'medalAbilityStormcallerMulti' },
    { text: 'Medal Sunbreaker Long Range*', value: 'medalAbilitySunbreakerLongRange' },
    { text: 'Everything Looks Like a Nail', value: 'medalAbilitySunbreakerMulti' },
    { text: 'Medal Voidwalker Distance*', value: 'medalAbilityVoidwalkerDistance' },
    { text: 'Medal Voidwalker Vortex*', value: 'medalAbilityVoidwalkerVortex' },
    { text: 'Blood for Blood', value: 'medalAvenger' },
    { text: 'I Live Here Now', value: 'medalControlAdvantageHold' },
    { text: 'Flag Bearer*', value: 'medalControlAdvantageStreak' },
    { text: 'Medal Control Capture All Zones*', value: 'medalControlCaptureAllZones' },
    { text: 'Flag Bearer*', value: 'medalControlMostAdvantage' },
    { text: 'Medal Control Perimeter Kill*', value: 'medalControlPerimeterKill' },
    { text: 'Power Overwhelming', value: 'medalControlPowerPlayWipe' },
    { text: 'Medal CountDown Defense*', value: 'medalCountdownDefense' },
    { text: 'Medal Countdown Defused Last Stand*', value: 'medalCountdownDefusedLastStand' },
    { text: 'Medal Countdown Defused Multi*', value: 'medalCountdownDefusedMulti' },
    { text: 'Medal Countdown Detonated*', value: 'medalCountdownDetonated' },
    { text: 'Medal Countdown Perfect*', value: 'medalCountdownPerfect' },
    { text: 'Gangs All Here', value: 'medalCountdownRoundAllAlive' },
    { text: 'The Cycle', value: 'medalCycle' },
    { text: 'Dodge This', value: 'medalDefeatHunterDodge' },
    { text: 'Barricade Breaker', value: 'medalDefeatTitanBrace' },
    { text: 'Rift Breaker', value: 'medalDefeatWarlockSigil' },
    { text: 'Not on My Watch', value: 'medalDefense' },
    { text: 'Crushed Them', value: 'medalMatchBlowout' },
    { text: 'Medal Match Comeback*', value: 'medalMatchComeback' },
    { text: 'Fight Me!', value: 'medalMatchMostDamage' },
    { text: 'Never In Doubt', value: 'medalMatchNeverTrailed' },
    { text: 'Time and a Half', value: 'medalMatchOvertime' },
    { text: 'Undefeated', value: 'medalMatchUndefeated' },
    { text: 'Double Play', value: 'medalMulti2x' },
    { text: 'Triple Play', value: 'medalMulti3x' },
    { text: 'Lights Out', value: 'medalMulti4x' },
    { text: 'Annihilation', value: 'medalMultiEntireTeam' },
    { text: 'Best Served Cold', value: 'medalPayback' },
    { text: 'Quick Strike', value: 'medalQuickStrike' },
    { text: 'Unyielding', value: 'medalStreak10x' },
    { text: 'Ruthless', value: 'medalStreak5x' },
    { text: 'We Ran Out of Medals', value: 'medalStreakAbsurd' },
    { text: 'Combined Fire', value: 'medalStreakCombined' },
    { text: 'Shutdown', value: 'medalStreakShutdown' },
    { text: 'Wrecking Crew', value: 'medalStreakTeam' },
    { text: 'Not So Fast My Friend', value: 'medalSuperShutdown' },
    { text: 'Medal Supremacy Crest Credit Streak*', value: 'medalSupremacyCrestCreditStreak' },
    { text: 'Medal Supremacy First Crest*', value: 'medalSupremacyFirstCrest' },
    { text: 'My Crest Is My Own', value: 'medalSupremacyNeverCollected' },
    { text: 'Medal Supremacy Perfect Secure Rate*', value: 'medalSupremacyPerfectSecureRate' },
    { text: 'Medal Supremacy Recover Streak*', value: 'medalSupremacyRecoverStreak' },
    { text: 'Safe and Secured', value: 'medalSupremacySecureStreak' },
    { text: 'Medal Survival Comeback*', value: 'medalSurvivalComeback' },
    { text: 'Undertaker', value: 'medalSurvivalKnockout' },
    { text: 'Medal Survival Quick Wipe*', value: 'medalSurvivalQuickWipe' },
    { text: 'Medal Survival Team Undefeated*', value: 'medalSurvivalTeamUndefeated' },
    { text: 'Survivor', value: 'medalSurvivalUndefeated' },
    { text: 'Medal Survival Win Last Stand*', value: 'medalSurvivalWinLastStand' },
    { text: 'Medal Unknown*', value: 'medalUnknown' },
    { text: 'Assault Specialist', value: 'medalWeaponAuto' },
    { text: 'Cold Fusion', value: 'medalWeaponFusion' },
    { text: 'Direct Hit', value: 'medalWeaponGrenade' },
    { text: 'Hawkeye', value: 'medalWeaponHandCannon' },
    { text: 'Lethal Cadence', value: 'medalWeaponPulse' },
    { text: 'Splash Damage', value: 'medalWeaponRocket' },
    { text: 'Field Scout', value: 'medalWeaponScout' },
    { text: 'Close Encounters', value: 'medalWeaponShotgun' },
    { text: 'Medal Sidearm*', value: 'medalWeaponSidearm' },
    { text: 'Sub Machinist', value: 'medalWeaponSmg' },
    { text: 'Medal Sniper Rifle*', value: 'medalWeaponSniper' },
    { text: 'Regent', value: 'medalWeaponSword' },
    { text: 'Most Precision Kills', value: 'mostPrecisionKills' },
    { text: 'Objectives Completed', value: 'objectivesCompleted' },
    { text: 'Opponents Defeated', value: 'opponentsDefeated' },
    { text: 'Orbs Dropped', value: 'orbsDropped' },
    { text: 'Orbs Gathered', value: 'orbsGathered' },
    { text: 'Precision Kills', value: 'precisionKills' },
    { text: 'Public Events Completed', value: 'publicEventsCompleted' },
    { text: 'Resurrections Performed', value: 'resurrectionsPerformed' },
    { text: 'Resurrections Received', value: 'resurrectionsReceived' },
    { text: 'Score', value: 'score' },
    { text: 'Time Played', value: 'secondsPlayed' },
    { text: 'Standing', value: 'standing' },
    { text: 'Suicides', value: 'suicides' },
    { text: 'Supremacy Ally Kill Enemy Crests Secured', value: 'supremacyAllyKillEnemyTagsCaptured' },
    { text: 'Supremacy Ally Crests Recovered', value: 'supremacyAllyTagsRecovered' },
    { text: 'Supremacy Crests Recovered', value: 'supremacyCrestsRecovered' },
    { text: 'Supremacy Crests Secured', value: 'supremacyCrestsSecured' },
    { text: 'Supremacy Own Kill Enemy Crests Secured', value: 'supremacyOwnKillEnemyTagsCaptured' },
    { text: 'Supremacy Own Crests Recovered', value: 'supremacyOwnTagsRecovered' },
    { text: 'Team Score', value: 'teamScore' },
    { text: 'Time Played Seconds', value: 'timePlayedSeconds' },
    { text: 'Total Activity Duration Seconds', value: 'totalActivityDurationSeconds' },
    { text: 'Total Death Distance', value: 'totalDeathDistance' },
    { text: 'Total Kill Distance', value: 'totalKillDistance' },
    { text: 'Unique Weapon Assist Damage', value: 'uniqueWeaponAssistDamage' },
    { text: 'Unique Weapon Assists', value: 'uniqueWeaponAssists' },
    { text: 'Unique Weapon Kills', value: 'uniqueWeaponKills' },
    { text: 'Unique Weapon Accuracy', value: 'uniqueWeaponKillsPrecisionKills' },
    { text: 'Unique Weapon Precision Kills', value: 'uniqueWeaponPrecisionKills' },
    { text: 'Ability Kills', value: 'weaponKillsAbility' },
    { text: 'Auto Rifle Kills', value: 'weaponKillsAutoRifle' },
    { text: 'Fusion Rifle Kills', value: 'weaponKillsFusionRifle' },
    { text: 'Grenade Kills', value: 'weaponKillsGrenade' },
    { text: 'Grenade Launcher Kills', value: 'weaponKillsGrenadeLauncher' },
    { text: 'Hand Cannon Kills', value: 'weaponKillsHandCannon' },
    { text: 'Machine Gun Kills', value: 'weaponKillsMachinegun' },
    { text: 'Melee Kills', value: 'weaponKillsMelee' },
    { text: 'Auto Rifle Accuracy', value: 'weaponKillsPrecisionKillsAutoRifle' },
    { text: 'Fusion Rifle Accuracy', value: 'weaponKillsPrecisionKillsFusionRifle' },
    { text: 'Grenade Accuracy', value: 'weaponKillsPrecisionKillsGrenade' },
    { text: 'Grenade Launcher  Accuracy', value: 'weaponKillsPrecisionKillsGrenadeLauncher' },
    { text: 'Hand Cannon Accuracy', value: 'weaponKillsPrecisionKillsHandCannon' },
    { text: 'Machine Gun Accuracy', value: 'weaponKillsPrecisionKillsMachinegun' },
    { text: 'Melee Accuracy', value: 'weaponKillsPrecisionKillsMelee' },
    { text: 'Pulse Rifle Accuracy', value: 'weaponKillsPrecisionKillsPulseRifle' },
    { text: 'Relic  Accuracy', value: 'weaponKillsPrecisionKillsRelic' },
    { text: 'Rocket Launcher Accuracy', value: 'weaponKillsPrecisionKillsRocketLauncher' },
    { text: 'Scout Rifle Accuracy ', value: 'weaponKillsPrecisionKillsScoutRifle' },
    { text: 'Shotgun Accuracy', value: 'weaponKillsPrecisionKillsShotgun' },
    { text: 'Sidearm  Accuracy', value: 'weaponKillsPrecisionKillsSideArm' },
    { text: 'Sniper Rifle Accuracy ', value: 'weaponKillsPrecisionKillsSniper' },
    { text: 'Submachine Gun Accuracy', value: 'weaponKillsPrecisionKillsSubmachinegun' },
    { text: 'Super Accuracy', value: 'weaponKillsPrecisionKillsSuper' },
    { text: 'Pulse Rifle Kills', value: 'weaponKillsPulseRifle' },
    { text: 'Relics Kills', value: 'weaponKillsRelic' },
    { text: 'Rocket Launcher Kills', value: 'weaponKillsRocketLauncher' },
    { text: 'Scout Rifle Kills', value: 'weaponKillsScoutRifle' },
    { text: 'Shotgun Kills', value: 'weaponKillsShotgun' },
    { text: 'Sidearm Kills', value: 'weaponKillsSideArm' },
    { text: 'Sniper Rifle Kills', value: 'weaponKillsSniper' },
    { text: 'Submachine Gun Kills', value: 'weaponKillsSubmachinegun' },
    { text: 'Super Kills', value: 'weaponKillsSuper' },
    { text: 'Sword Kills', value: 'weaponKillsSword' },
    { text: 'Auto Rifle Precision Kills', value: 'weaponPrecisionKillsAutoRifle' },
    { text: 'Fusion Rifle Precision Kills', value: 'weaponPrecisionKillsFusionRifle' },
    { text: 'Grenade Precision Kills', value: 'weaponPrecisionKillsGrenade' },
    { text: 'Grenade Launcher Precision Kills', value: 'weaponPrecisionKillsGrenadeLauncher' },
    { text: 'Hand Cannon Precision Kills', value: 'weaponPrecisionKillsHandCannon' },
    { text: 'Machine Gun Precision Kills', value: 'weaponPrecisionKillsMachinegun' },
    { text: 'Melee Precision Kills', value: 'weaponPrecisionKillsMelee' },
    { text: 'Pulse Rifle Precision Kills ', value: 'weaponPrecisionKillsPulseRifle' },
    { text: 'Relic Precision Kills', value: 'weaponPrecisionKillsRelic' },
    { text: 'Rocket Launcher Precision Kills', value: 'weaponPrecisionKillsRocketLauncher' },
    { text: 'Scout Rifle Precision Kills', value: 'weaponPrecisionKillsScoutRifle' },
    { text: 'Shotgun Precision Kills', value: 'weaponPrecisionKillsShotgun' },
    { text: 'Sidearm Precision Kills', value: 'weaponPrecisionKillsSideArm' },
    { text: 'Sniper Rifle Precision Kills', value: 'weaponPrecisionKillsSniper' },
    { text: 'Submachine Gun Precision Kills', value: 'weaponPrecisionKillsSubmachinegun' },
    { text: 'Super Precision Kills', value: 'weaponPrecisionKillsSuper' },
    { text: 'Win/Loss Ratio', value: 'winLossRatio' }
  ]
}
